### PR TITLE
Fixed a few cases where `setLocked` didn't lock.

### PR DESCRIPTION
**Pull request by sompylasar**
- Fixes https://github.com/projectstorm/react-diagrams/issues/71
- Fixes https://github.com/projectstorm/react-diagrams/issues/73

### CODE REVIEW

**Comment by dylanvorster** [comment]
thanks for the pull request, I'm going to need some time to review the changes :)

**Comment by chlumper** [comment]
@dylanvorster do you have any schedule when you'll find time to review the changes of the PR and release updated npm packages of the library?
looking forward since we would need exactly these changes!

**Comment by dylanvorster** [comment]
Hi @chlumper , so some issues:
• I recently did a massive upgrade of the library which moved the whole thing to TSX, so there is going to be merge issues there
• Im not happy with the weird setInterval in one of the demos
• we are not using _fields to represent private members, as this is handled by the typescript compile. private fields, vars should rather explicitly make use of the private keywords
 • Im a  bit concerned about the number of places where the additional logic is applied for set locks. Im going to try and take a look at it this sunday, to see if I can't make use to the parent/child lock model that is already in place.

**Comment by sompylasar** [comment]
If you started talking like this, I'm "a bit concerned" about the UI state scattered around stateful objects, observables that don't trigger on computed state changes, and `forceUpdate` everywhere to make React work with this stuff, including "weird setTimeout" with additional `forceUpdate` where just one `forceUpdate` didn't work.

Conversion to JSX refactor by now didn't change this state management approach that causes many rendering issues. Centralizing the state storage and changes to the state in one immutable plain JS object tree will resolve all if them, including those listed above ("too many places where we check isLocked").

**Comment by dylanvorster** [comment]
well you are more than welcome to completely rewrite the library in a redux fashion. If you claim you are able to achieve the same thing, or improve on it and make it more performant using such a method, then please don't let me stop you. Im voicing concerns here, because it is YOUR changes that you want ME to merge in. You are welcome to throw around things like 'observerables' when what I actually use is an observer pattern( which is quite different to things like mobx), but if you can help it, don't interpret my comments as "I think your code is shit", which is very much not the case. Im saying that if you want me to include your changes, then it needs to go through some code review.

I feel I should also just mention that "this state management approach that causes many rendering issues" is actually a trade off. This state management approach also has many wins in both UI performance as well as with extensibility. The very first iteration of this library worked closely in a manner you mentioned, but the amount of pure functions required to achieve the same result became a massive pain to maintain and work with. This is why the system was designed now in layers. You can have a central tree than you modify and parse it through the engine that spits out a scene graph.

Diagramming is hard, its not a one size fits all.

**Pull request closed without merging**
