### PR TITLE
Support React 17 (Fixes #751)

### LINKED ISSUE #751: Release new version compatible with React 17
React 17 was just released. There are no breaking changes, but if I try to use it with react-diagrams, I get warnings about missing peer-dependencies (react-diagrams depends on react@16.x). 

Can you release a new version making this package compatible with React 17? @dylanvorster

### PR DESCRIPTION
**Pull request by alexandernst**
# Checklist

- [x] The code has been run through pretty `yarn run pretty`
- [x] The tests pass on CircleCI
- [x] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [x] The PR Template has been filled out (see below)
- [x] Had a beer/coffee because you are awesome

## What?

Upgrade to React 17

## Why?

Because it will provide better support in the long term.

## How?
 
By upgrading all libraries that haven't been upgraded to React 17 (bugging their creators), then updating this library.

### CODE REVIEW

**Comment by alexandernst** [comment]
This fixes #751

**Comment by dylanvorster** [comment]
Feels like we should just go all in with 17, and not even worry about 16, thoughts?

**Comment by alexandernst** [comment]
It doesn't hurt to leave React 16, at least for the moment. Even if 16 and 17 are completely compatible, a lot of projects haven't updated yet their peer dependencies, which means that if you leave only React 17, people will get warnings as the one I added in #751. It won't break anything, but it  will show warnings when running "yarn install".

**Comment by alexandernst** [comment]
@dylanvorster Is there anything else I should add to this?

**Comment by dylanvorster** [comment]
Upgraded all the deps, its now in master

**Pull request closed without merging**
