### PR TITLE
Enable/disable canvas drag

### PR DESCRIPTION
**Pull request by bogomya**
# Checklist

- [x] The code has been run through pretty `yarn run pretty`
- [x] The tests pass on CircleCI
- [x] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [x] The PR Template has been filled out (see below)
- [x] Had a beer/coffee because you are awesome

## What?
Adding the ability to fix the canvas

## Why?
https://github.com/projectstorm/react-diagrams/issues/570

## How?
 Add control by adding config to DragCanvasState

## Feel good image:
LOL

### CODE REVIEW

**Comment by bogomya** [comment]
@dylanvorster please review

**Comment by Vakintoshka** [comment]
👍

**Comment by sarastef** [comment]
it is available on the last version(6.2.0)?

**Comment by KirbyAbadilla** [comment]
It seems that this is not added in v6.2.0, the changes in the DragCanvasState constuctor is not reflected

**Pull request merged**
