### PR TITLE
PR #130 Refactor

### PR DESCRIPTION
**Pull request by dylanvorster**
This refactor works off of the work done by PR #130 and makes the cloning slightly more robust.

### CODE REVIEW

**Comment by dylanvorster** [comment]
Jest is fighting me -_-

**Comment by dylanvorster** [comment]
YES!!!!!

**Comment by danielg2002** [comment]
@dylanvorster Hi Dylan, when you expect release a new version with this PR ?

**Comment by dylanvorster** [comment]
soon :)

**Comment by danielg2002** [comment]
@dylanvorster ok, thanks.! great work!

I'm using your library in a new project and it's awesome, soon I will share with you some screens and customizations I did, in particular the idea of "Default port" just to create a link using the whole area of the target node.

**Pull request merged**
