### PR TITLE
Link customisation prototype

### PR DESCRIPTION
**Pull request by kfrajtak**
Hi,
I have been experimenting with your code and thanks to the architecture I was able to create a small demo (with some minor changes) that showcases how to change the style (in this case stroke width) of the link. A new story was added to the storybook.
Some parts need some polishing (see src/defaults/DefaultLinkWidget.tsx line 92) and more work might be required.
Are you planning to style the links more - adding arrows, labels, etc.?
Thanks for review :) 
Karel

image

### CODE REVIEW

**Comment by dylanvorster** [comment]
Hey! This is a really good addition to the library, and I see where you are going with it. I made some changes that show how you can do a lot of this, without needing to intercept the props and make as many changes to the core. please merge these changes in:

https://github.com/projectstorm/react-diagrams/tree/kfrajtak-master

**Comment by dylanvorster** [comment]
You will notice that I removed a lot of code but retained the same amount of functionality :)

**Comment by kfrajtak** [comment]
Sorry, I am not sure where to look for the changes you made and what to do next.
Thanks for help.

**Comment by dylanvorster** [comment]
my bad https://github.com/projectstorm/react-diagrams/commit/77b2ee6f76adf95f067b2983fd22c640c00b6f54

**Comment by kfrajtak** [comment]
I have added comments to 77b2ee6.

**Comment by kfrajtak** [comment]
I have added some comments to 77b2ee6.

**Comment by dylanvorster** [comment]
I've added some comments as well, merge in the code to this PR and you will see what I mean :)

**Comment by kfrajtak** [comment]
Ok. Thanks for the comments.

> merge in the code to this PR

How to do that? (silly question, I know) Should I do it manually based on your comments?

**Pull request merged**
