### PR TITLE
Fix #683 and #599; Drag and drop no longer crashes

### LINKED ISSUE #599: Can not integrate into react-boilerplate
Hi, thank you for the amazing package.
I tried to integrate this package in my react project that uses `React-Boilerplate` (https://github.com/react-boilerplate/react-boilerplate)
But I got an error: `a.default is not constructor`.
Can anyone help me?
Thanks!

### LINKED ISSUE #683: Drag and Drop crashes
I have observed this issue when trying to integrate `react-diagrams` within my app initialized with `react-boilerplate`.

I have been able to reproduce the issue in the following CodeSandbox: https://codesandbox.io/s/react-diagrams-drag-and-drop-crash-el9d2

This doesn't seem to happen in an app initialized with create-react-app, as can be seen in the following CodeSandbox: https://codesandbox.io/s/react-diagrams-drag-and-drop-success-ti7cw

Since these both contain the same code aside for the `webpack` and `babel` configurations this leads me to believe that it is not something specific to `react-boilerplate`.

The specific error messages I received in the console are 
```Uncaught TypeError: a.default is not a constructor at l.componentDidMount (index.js?d9df:9)...```
and
```Uncaught TypeError: Cannot read property 'disconnect' of undefined at l.componentWillUnmount (index.js?d9df:9)...```

This seems to be related to https://github.com/projectstorm/react-diagrams/issues/599 hence my comment there, but seems to be broader then described there, so I opened a new issue.

### PR DESCRIPTION
**Pull request by RELnemtzov**
# Checklist

- [v] The code has been run through pretty `yarn run pretty`
- [?] The tests pass on CircleCI
- [v] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [v] The PR Template has been filled out (see below)
- [vvvvv] Had a beer/coffee because you are awesome

## What?
As detailed in #683 the library crashes under some conditions when using drag-and-drop.
This should also fix #599 which is what I used as a base for my project, where it works with this fix.

## Why?
The `resize-observer-polyfill` was not able to initialize and was crashing the app on drag-and-drop.

## How?
 This seems to be because of not importing the `resize-observer-polyfill` properly.

## Feel good image:

I got your back

### CODE REVIEW

**Comment by dylanvorster** [comment]
going to test this locally in a bit

**Comment by RELnemtzov** [comment]
Any chance of this getting merged?

**Comment by dylanvorster** [comment]
yeah this is breaking on my side :( I think the issue might be related to synthetic defaults in the project you are building react diagrams into

**Comment by RELnemtzov** [comment]
Thanks for pointing me in the right direction.
My project is actually not in TypeScript so I don't even have a `tsconfig.json`. Even trying to adding a `tsconfig.json` with `allowSyntheticDefaultImports: true` along with a `ts-loader` configuration for webpack didn't solve the issue on my project.

Adding `allowSyntheticDefaultImports: true` on it's own to this project didn't help either. **However** adding `esModuleInterop:  true` to the main `tsconfig.json` in this project **did** work. Then I was getting typechecking errors in IntelliJ without adding `allowSyntheticDefaultImports: true` as well.

I've updated the PR accordingly. I hope that this will work for you and we can merge.

**Comment by snufkin877** [comment]
@dylanvorster Hellow Dylan, any chance you can review this PR and merge it? It solves the issue in many others project with react-boilerplate. Thanks

**Comment by wader** [comment]
Hello! could this be related to https://github.com/evanw/esbuild/issues/391 ?

**Comment by maxtsh** [comment]
Found the solution, downgrade or upgrade to resize-observer-polyfill AT version 1.0.0 on react boilerplate will fix the issue.

**Pull request closed without merging**
