### PR TITLE
5.0.0 (WIP)

### PR DESCRIPTION
**Pull request by dylanvorster**
# Checklist

- [x] The code has been run through pretty `yarn run pretty`
- [x] The tests pass on CircleCI
- [x] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [x] The PR Template has been filled out (see below)

Beers had:
- [x] 1
- [x] 2
- [x] 3
- [x] 4

### TODO

- [x] Cant create point on simple demo
- [x] Cant link two nodes together
- [x] Labels are not done yet

## What?

* Spliced up the DefaultLinkWidget so that the concept of the 'default link' can be extended with custom link segments. 
* Provided more helper methods to the default pack to make it easier to construct diagrams without always having to instantiate many models.
* Flow Support
* Smart Routing
* API improvements
* Bootstrap improvements
* Labels are now first class citizens and have their own models

## Why?

While you have always been able to provide your own link entirely, there are a number of cases where we want to have a visually completely different link to the DefaultLink, but one that performs in the same way without having to re-engineer it completely. It makes more sense to make the DefaultWidget more dynamic and pluggable which should cater for 90% of extensible use cases. For the other 10%, you can just provide a new link like you normally would have before this PR.

Labels are also really cool, but I think we should treat labels like other widgets since they are visual, and this we need supporting models and factories to really get more power out of them, so it made sense to refactor them out.

Flow support makes it easier to create diagrams that act as system designers in that you don't need to worry about no-ops such as dangling links and tricky link ux that just slows down graph creation

To further aid flow support, smart routing automatically handles path generation and routing so that the links avoid all other entities on the graph.

## How?

* Make better use of the DefaultLinkFactory to return the link segments as well
* Provide helper methods in the node, link and port models
* Move some common logic to the toolkits
* Introduce a "DefaultLinkModel"
* Rewrite almost all of the demos to use the new simplified syntax x_x
* Merged in PR 147 (really cool flow support)
* Labels are now first class citizens (models, factories etc..) (WIP)
* Merged in PR 161 (really cool smart routing support)
* Improve custom link demo
* Create a testing framework onto of jest + puppeteer to easily do end to end testing
* automatically load the all the demos for jest snapshot testing 
* Introduce a BEM widget
* Refactor all styles to use BEM
* In a smart manner, allow all widgets to pass extra props to the component itself

Shoutouts to:

@klauspaiva (smart routing)
@yngndrw (flow support)

^ These are some of the coolest PR's I've seen yet

## Feel-Good "programming lol" image:

LOL

### CODE REVIEW

**Comment by dylanvorster** [comment]
@klauspaiva You might find this PR relevant to the changes you are busy with (which I really hope you decide to put into a PR :P)

https://lh5.ggpht.com/0Lth0ERywfW-9-K6_pOaye3Yirqiqhcx_IMvcuV3n24JUTPnc-EvSisg2hxUsH4jN5g=w300

**Comment by klauspaiva** [comment]
Nice, that's a great re-factoring effort, dude!

Yeah, I can see a couple, maybe 10, maybe 100 merge conflicts haha, but don't worry, I still need to handle multiple points and then simplify the code before it becomes PR ready, so I'll tackle them later on.

Thanks for the heads up!

**Comment by dylanvorster** [comment]
@klauspaiva cool, your branch has been merged in, I'm still going to refactor a few things but its all working :)

**Comment by dylanvorster** [comment]
labels are go!

**Comment by dylanvorster** [comment]
Custom link demos are back and they animate :D
animate

**Comment by dylanvorster** [comment]
Tests are now end to end and test actual functionality by clicking on ports and dragging nodes etc..

**Comment by dylanvorster** [comment]
TESTS PASS! YASSSS!!!!

**Comment by dylanvorster** [comment]
BEM all the things

**Comment by dylanvorster** [comment]
screen shot 2018-02-25 at 11 26 35

**Pull request merged**
