### PR TITLE
Features/labview style of routes

### PR DESCRIPTION
**Pull request by DanieLazarLDAPPS**
# Checklist

- [ ] The code has been run through pretty `yarn run pretty`
- [x] The tests pass on CircleCI
- [ ] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [x] The PR Template has been filled out (see below)
- [x] Had a beer because you are awesome

## What?

New "right-angle" style like LabView for example. It is more engineering way how to route things e.g electronic schematic. Check new routing
rightanglerouting
newroute

**NOTE 1:** I placed it into routes/rightAngles just because I am not really familiar with the whole structure and plans how to restructure it. 

**NOTE 2** If this will be merged we should consider mutual function for DefaultLinkWidget and RightAngleLinkWidget. I mean **addPointToLink, generatePoint, generateLabel, generateLink, findPathAndRelativePositionToRenderLabel, calculateLabelPosition** and we should place it to abstract class or something.

## Why?

Because it is not available in this project. Smart routing is nice but I can't move the path.

## How?

It is a new feature some it just takes some time to develop it :)

## Feel-Good "programming lol" image:

(Add your own one below :])

image

### CODE REVIEW

**Comment by dylanvorster** [comment]
Wow this is amazing, I'm going to have to refactor this a lot though to get it into the new `lerna` branch which already addresses `addPointToLink, generatePoint, generateLabel, generateLink, findPathAndRelativePositionToRenderLabel, calculateLabelPosition`

**Comment by DanieLazarLDAPPS** [comment]
> Wow this is amazing, I'm going to have to refactor this a lot though to get it into the new `lerna` branch which already addresses `addPointToLink, generatePoint, generateLabel, generateLink, findPathAndRelativePositionToRenderLabel, calculateLabelPosition`

Sounds Good, Thanks. **RightAngleLinkFactory** and **RightAngleLinkFactory** this will be still available after your refactor ? I mean I just want to import it to my project and use it and hope that it will remain the same after your refactor.

**Comment by frank-martinez-27** [comment]
Hello all.

First I think this makes the edges look even better, so great job!

Second, in my case I have the IN port at the top of the node and the OUT port on the bottom. Since my diagrams have a top-down look, the edges look funky because it goes from the root node all the way down and then immediately left/right to connect to the IN port, so it looks like the letter L. I’m your approach you were able to create an extra point on the edge giving you an extra angle and made it look better, do you think your approach would help me with my edges on a top-down diagram?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DanieLazarLDAPPS** [comment]
@frank-martinez-27 I think it should be independent if the diagram is from left to right or from top to bottom. So you would say "yes" this should help you ... Just register factory RightAngleLinkFactory as it is in demos/demo-right-angles-routing and try it.

**Comment by frank-martinez-27** [comment]
@DanieLazarLDAPPS You were right, I pulled your forked version and tested your fix for my top-down and works. I wanted to verify if it works with smart-routing enabled but seems it doesn't. Can you check it?

image

**Comment by DanieLazarLDAPPS** [comment]
@frank-martinez-27 Well it will not work right now check this code snippet in DefaultLinkWidget
`
isSmartRoutingApplicable(): boolean {
		const { diagramEngine, link } = this.props;

		if (!diagramEngine.isSmartRoutingEnabled()) {
			return false;
		}

		if (link.points.length !== 2) {
			return false;
		}

		if (link.sourcePort === null || link.targetPort === null) {
			return false;
		}

		return true;
	}
`

As you can see there is a condition to have only two points for a link. But I am using points to render 90° style of routes so there is all the time at least 3 points which breaks this condition. I can later dive into code snippet providing a smart route. Maybe I can use it for just for the path between two-points and let's see if it will work. But I think if it will be rendered by this smart function than user will not be available to use moving which can be confusing later. So the solution is to add more points into the route to enable functionality as it expected by the end-user.
`
const smartLink = this.pathFinding.calculateLinkStartEndCoords(routingMatrix, directPathCoords);

			if (smartLink) {
				const { start, end, pathToStart, pathToEnd } = smartLink;

				// second step: calculate a path avoiding hitting other elements
				const simplifiedPath = this.pathFinding.calculateDynamicPath(
					routingMatrix,
					start,
					end,
					pathToStart,
					pathToEnd
				);
`

**Comment by dylanvorster** [comment]
Im going to try and get this merged in to the lerna branch, will let all of you know when ive got something working.

**Comment by dylanvorster** [comment]
> Sounds Good, Thanks. **RightAngleLinkFactory** and **RightAngleLinkWidget** this will be still available after your refactor ? I mean I just want to import it to my project and use it and hope that it will remain the same after your refactor.

Also yes, thats how it will work, its just that the new system is much more modular so we can definitely make use of the new primitives to just add your code which does the path itself and not the labels

**Comment by DanieLazarLDAPPS** [comment]
@frank-martinez-27 check this https://github.com/DanieLazarLDAPPS/react-diagrams/tree/features/labview-style-of-routes-enable-smart I enabled smart routing but in some case, it is not working nice. Since I am not familiar with smart routing I can't quick help you out. But @dylanvorster wrote somewhere that he is rewriting smart routing so let's see how it will work later.

Screenshot from 2019-08-07 20-31-24
Screenshot from 2019-08-07 20-31-18

Check the differences so the best will be if the smart route will bypass node as close as possible.

**Comment by DanieLazarLDAPPS** [comment]
Hi @dylanvorster So what is our strategy should I rewrite pull request? If yes where to put new link style? react-diagram-routing/src/link/<FACTORY, MODEL, WIDGET> ?

**Comment by dylanvorster** [comment]
Think that would be best, once its working I will make some adjustments to bring it in line with the new state manager etc.. :)

**Comment by DanieLazarLDAPPS** [comment]
Hi, @dylanvorster  So I migrated PR to the new version so it is ready for review.

**Comment by dylanvorster** [comment]
:amaze: that was fast. I will have a look this evening ❤️

**Comment by dylanvorster** [comment]
This is literally incredible .

**Pull request merged**
