### PR TITLE
Hotfix: fix zooming when canvas not in the top left corner

### PR DESCRIPTION
**Pull request by JokerNN**
Also I'm extremely sorry for creating so many problems in Friday's evening.

### CODE REVIEW

**Comment by dylanvorster** [comment]
Lol, thats okay xD Could you add a demo that illustrates what this fixes if possible? Take a look at the demos folder and add it there (if its not too much trouble)

**Comment by dylanvorster** [comment]
Is it a fix for this: http://www.projectstorm.io/react-diagrams/?selectedKind=React%20Diagrams&selectedStory=Embedded%20diagram&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel?

**Comment by dylanvorster** [comment]
Awesome, it works!

**Comment by JokerNN** [comment]
Yes, fix for this indeed
GIF

**Comment by dylanvorster** [comment]
3.1.2

**Pull request merged**
