### PR TITLE
initial work on group nodes support

### PR DESCRIPTION
**Pull request by dylanvorster**
# Checklist

- [ ] The code has been run through pretty `yarn run pretty`
- [ ] The tests pass on CircleCI
- [ ] You have referenced the issue(s) or other PR(s) this fixes/relates-to
- [ ] The PR Template has been filled out (see below)
- [ ] Had a beer because you are awesome

## What?

(My awesome new feature does this really cool thing.)

## Why?

(Because obviously it could not do it before)

## How?

(Basically I did this and that because im a super 1337 hacker) 

## Feel-Good "programming lol" image:

(Add your own one below :])

LOL

### CODE REVIEW

**Comment by cemremengu** [comment]
Nice work! Any examples on how to use it? Wanna give a try even if it works with bugs

**Comment by dakshika** [comment]
Any update on merging this to master?

**Comment by dylanvorster** [comment]
@dakshika @cemremengu see https://github.com/projectstorm/react-diagrams/issues/27#issuecomment-376208958

**Comment by dylanvorster** [comment]
https://github.com/projectstorm/react-canvas

**Comment by dylanvorster** [comment]
Closing in favour of storm-react-canvas which literally solves this problem a whole lot better

**Pull request closed without merging**
